#!/bin/bash

su -c "echo 3 >'/proc/sys/vm/drop_caches' && swapoff -a && swapon -a && printf '\n%s\n' 'Ram-cache and Swap Cleared'" root

ARGS=$*

/usr/bin/pvremove -y -ff "${ARGS}*"
/usr/bin/dmsetup remove_all
/usr/bin/wipefs -af "${ARGS}"
#/usr/bin/dd if=/dev/zero of="${ARGS}" bs=1k count=8192
