#!/bin/bash
#Seguimento do vídeo de EF
loadkeys pt-latin1
rfkill unblock wifi
ip link set wlan0 up
connmanctl scan wifi
connmanctl agent on
connmnnctl connect wifi_........ | type in password

#montar as partições

#instalar inicialmente o software de *raiz*
basestrap /mnt base-devel runit elogind-runit linux-hardened linux-hardened-headers rkhunter sysstat  linux-firmware vim intel-ucode

fstabgen -U /mnt >> /mnt/etc/fstab

chroot /mnt 
#criar swapfile ... apenas para uefi -->> "dd if=/dev/zero of=/swapfile bs=1G count status=progress" (são 2x 1G de swap) PERMISSÕES??
# por EF é chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile # introduzir no fstab

ln -sf /usr/share/zoneinfo/Europe/Lisbon /etc/localtime
hwclock --systohc
vim /etc/locale.gen
locale-gen
vim /etc/locale.conf # LANG=pt_PT.UTF-8

pacman -S grub ou 2 ef9ibootmgr networkmanager networkmanager-runit network-manager-applet dosfstools bluez bluez-runit bluez-utils cups cups-runit xdg-utils xdg-user-dirs xdg-desktop-portal-wlr dialog wpa_supplicant wpa_supplicant-runit mtools reflector gvfs gvfs-smb nfs-utils inetutils dnsutils cups hplip alsa-utils pulseaudio 

grub-install --target... (para UEFI e MBR)

grub-mkconfig -o /boot/grub/grub.cfg

useradd -mG wheel groot
passwd groot

umount -R /mmt
reboot

pause...









